# Generated by Django 3.2.12 on 2022-06-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
