# Generated by Django 3.2.12 on 2022-06-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_problem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
