# Generated by Django 3.2.12 on 2022-06-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_alter_problem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problemcode',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
