# Generated by Django 3.2.12 on 2022-06-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20220630_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problemcode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
