# Generated by Django 3.2.12 on 2022-06-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_problem_problemcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='correctoutput',
            field=models.TextField(default=''),
        ),
    ]
