# Generated by Django 3.2.12 on 2022-07-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_testcases'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProblemsHavingTags',
            new_name='ProblemsHavingTag',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameModel(
            old_name='Testcases',
            new_name='Testcase',
        ),
    ]
