# Generated by Django 3.2.12 on 2022-07-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_auto_20220701_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='correctoutput',
        ),
        migrations.AddField(
            model_name='problem',
            name='testcasesinputandoutput',
            field=models.TextField(default=''),
        ),
    ]
