# Generated by Django 3.2.12 on 2022-07-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0012_auto_20220701_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(to='problem.Tag'),
        ),
        migrations.DeleteModel(
            name='ProblemsHavingTag',
        ),
    ]
