# Generated by Django 3.2.12 on 2022-07-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0013_auto_20220702_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='testcasesinputandoutput',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='title',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
