# Generated by Django 3.2.12 on 2022-07-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_user'),
        ('problem', '0014_auto_20220702_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
