# Generated by Django 3.2.12 on 2022-07-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_testcase_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='user',
        ),
    ]
