# Generated by Django 3.2.12 on 2023-06-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_stats_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='attempted',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='stats',
            name='solved',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='stats',
            name='unsolved',
            field=models.JSONField(default=list),
        ),
    ]
